version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    open-pull-requests-limit: 1
    target-branch: main
    reviewers:
      - mryhryki
    assignees:
      - mryhryki
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    target-branch: main
    reviewers:
      - mryhryki
    assignees:
      - mryhryki
    labels:
      - dependencies
