name: publish_to_npm

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish_to_npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v; deno --version;
      - name: Set branch name
        run: |
          echo "BRANCH=release-$(date +'%Y%m%d-%H%M%S')" >> "${GITHUB_ENV}"
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git switch -c "${BRANCH}"
      - name: Update version
        run: npm version ${{ github.event.inputs.bump_type }}
      - name: Set version
        run: |
          echo VERSION="v$(cat package.json | jq -r '.version')" >> "${GITHUB_ENV}"
      - name: Set AuthToken for npmjs.com
        run: echo "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}" > "${HOME}/.npmrc"
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Create Pull Request
        run: |
          git switch -c "release/${VERSION}"
          git push origin "release/${VERSION}"
          gh pr create --title "Release ${VERSION}" --body "Created by [publish_to_npm.yaml]()" --reviewer "mryhryki"
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Publish to npmjs.com
        run: npm publish
      - name: Push tag
        run: git push --tags
